version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - server
    networks:
      - meet-chat-app
  client:
    build: ./client
    ports:
      - "5173" # Changed to 3001 to avoid conflict
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server
    networks:
      - meet-chat-app

  server:
    build: ./server
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - meet-chat-app

networks:
  meet-chat-app:
