version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:5173" # Browser -> container:5173
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
